//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool. Changes to this file may cause
//     incorrect behavior and will be lost if the code is regenerated.
//     To update, edit Messages.resx and regenerate using ResXFileCodeGenerator.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Globalization;
using System.Resources;

namespace NetInventory.Resources;

public static class Messages
{
    private static readonly ResourceManager _resourceManager =
        new("NetInventory.Resources.Messages", typeof(Messages).Assembly);

    private static CultureInfo? _culture;

    /// <summary>Culture used for all resource lookups. Defaults to current UI culture.</summary>
    public static CultureInfo? Culture
    {
        get => _culture;
        set => _culture = value;
    }

    // ═══════════════════════════════════════════════════
    // ERRORES DE DOMINIO / NEGOCIO
    // ═══════════════════════════════════════════════════

    /// <summary>El producto no existe.</summary>
    public static string Error_ProductNotFound =>
        _resourceManager.GetString(nameof(Error_ProductNotFound), _culture)!;

    /// <summary>La cantidad solicitada supera el stock disponible.</summary>
    public static string Error_StockNegative =>
        _resourceManager.GetString(nameof(Error_StockNegative), _culture)!;

    /// <summary>Ya existe un producto con ese SKU.</summary>
    public static string Error_SkuDuplicated =>
        _resourceManager.GetString(nameof(Error_SkuDuplicated), _culture)!;

    /// <summary>La cantidad debe ser mayor a cero.</summary>
    public static string Error_InvalidQuantity =>
        _resourceManager.GetString(nameof(Error_InvalidQuantity), _culture)!;

    /// <summary>Credenciales inválidas.</summary>
    public static string Error_InvalidCredentials =>
        _resourceManager.GetString(nameof(Error_InvalidCredentials), _culture)!;

    /// <summary>Refresh token inválido o expirado.</summary>
    public static string Error_InvalidRefreshToken =>
        _resourceManager.GetString(nameof(Error_InvalidRefreshToken), _culture)!;

    /// <summary>Usuario no encontrado.</summary>
    public static string Error_UserNotFound =>
        _resourceManager.GetString(nameof(Error_UserNotFound), _culture)!;

    /// <summary>Recurso no encontrado.</summary>
    public static string Error_NotFound =>
        _resourceManager.GetString(nameof(Error_NotFound), _culture)!;

    /// <summary>Error interno del servidor.</summary>
    public static string Error_Internal =>
        _resourceManager.GetString(nameof(Error_Internal), _culture)!;

    /// <summary>Error al registrar el usuario.</summary>
    public static string Error_RegistrationFailed =>
        _resourceManager.GetString(nameof(Error_RegistrationFailed), _culture)!;

    // ═══════════════════════════════════════════════════
    // VALIDACIONES — PRODUCTOS
    // ═══════════════════════════════════════════════════

    /// <summary>El nombre es obligatorio.</summary>
    public static string Val_Product_NameRequired =>
        _resourceManager.GetString(nameof(Val_Product_NameRequired), _culture)!;

    /// <summary>El nombre no puede superar 200 caracteres.</summary>
    public static string Val_Product_NameMaxLength =>
        _resourceManager.GetString(nameof(Val_Product_NameMaxLength), _culture)!;

    /// <summary>El SKU es obligatorio.</summary>
    public static string Val_Product_SkuRequired =>
        _resourceManager.GetString(nameof(Val_Product_SkuRequired), _culture)!;

    /// <summary>El SKU no puede superar 50 caracteres.</summary>
    public static string Val_Product_SkuMaxLength =>
        _resourceManager.GetString(nameof(Val_Product_SkuMaxLength), _culture)!;

    /// <summary>La tabla de categoría es obligatoria.</summary>
    public static string Val_Product_CategoryTableRequired =>
        _resourceManager.GetString(nameof(Val_Product_CategoryTableRequired), _culture)!;

    /// <summary>La categoría es obligatoria.</summary>
    public static string Val_Product_CategoryRequired =>
        _resourceManager.GetString(nameof(Val_Product_CategoryRequired), _culture)!;

    /// <summary>El código de categoría no puede superar 20 caracteres.</summary>
    public static string Val_Product_CategoryCodeMaxLength =>
        _resourceManager.GetString(nameof(Val_Product_CategoryCodeMaxLength), _culture)!;

    /// <summary>El precio no puede ser negativo.</summary>
    public static string Val_Product_PriceNotNegative =>
        _resourceManager.GetString(nameof(Val_Product_PriceNotNegative), _culture)!;

    /// <summary>El ID del producto es obligatorio.</summary>
    public static string Val_Product_IdRequired =>
        _resourceManager.GetString(nameof(Val_Product_IdRequired), _culture)!;

    // ═══════════════════════════════════════════════════
    // VALIDACIONES — CONFIGURACIONES DE AUDITORÍA
    // ═══════════════════════════════════════════════════

    /// <summary>El ID es obligatorio.</summary>
    public static string Val_AuditConfig_IdRequired =>
        _resourceManager.GetString(nameof(Val_AuditConfig_IdRequired), _culture)!;

    /// <summary>El método HTTP es obligatorio.</summary>
    public static string Val_AuditConfig_HttpMethodRequired =>
        _resourceManager.GetString(nameof(Val_AuditConfig_HttpMethodRequired), _culture)!;

    /// <summary>El método debe ser GET, POST, PUT, DELETE, PATCH o * (todos).</summary>
    public static string Val_AuditConfig_HttpMethodInvalid =>
        _resourceManager.GetString(nameof(Val_AuditConfig_HttpMethodInvalid), _culture)!;

    /// <summary>El patrón de URL es obligatorio.</summary>
    public static string Val_AuditConfig_UrlPatternRequired =>
        _resourceManager.GetString(nameof(Val_AuditConfig_UrlPatternRequired), _culture)!;

    /// <summary>El patrón no puede superar 500 caracteres.</summary>
    public static string Val_AuditConfig_UrlPatternMaxLength =>
        _resourceManager.GetString(nameof(Val_AuditConfig_UrlPatternMaxLength), _culture)!;

    /// <summary>El patrón debe comenzar con '/'.</summary>
    public static string Val_AuditConfig_UrlPatternStartsWithSlash =>
        _resourceManager.GetString(nameof(Val_AuditConfig_UrlPatternStartsWithSlash), _culture)!;

    /// <summary>La descripción es obligatoria.</summary>
    public static string Val_AuditConfig_DescriptionRequired =>
        _resourceManager.GetString(nameof(Val_AuditConfig_DescriptionRequired), _culture)!;

    /// <summary>La descripción no puede superar 200 caracteres.</summary>
    public static string Val_AuditConfig_DescriptionMaxLength =>
        _resourceManager.GetString(nameof(Val_AuditConfig_DescriptionMaxLength), _culture)!;

    // ═══════════════════════════════════════════════════
    // ERRORES — VALUE OBJECTS
    // ═══════════════════════════════════════════════════

    /// <summary>El SKU no puede estar vacío.</summary>
    public static string Error_SkuEmpty =>
        _resourceManager.GetString(nameof(Error_SkuEmpty), _culture)!;

    /// <summary>El SKU no puede superar los 50 caracteres.</summary>
    public static string Error_SkuTooLong =>
        _resourceManager.GetString(nameof(Error_SkuTooLong), _culture)!;

    /// <summary>El precio no puede ser negativo.</summary>
    public static string Error_MoneyNegative =>
        _resourceManager.GetString(nameof(Error_MoneyNegative), _culture)!;

    // ═══════════════════════════════════════════════════
    // ERRORES — AUDIT CONFIGS
    // ═══════════════════════════════════════════════════

    /// <summary>Configuración de auditoría no encontrada.</summary>
    public static string Error_AuditConfigNotFound =>
        _resourceManager.GetString(nameof(Error_AuditConfigNotFound), _culture)!;

    // ═══════════════════════════════════════════════════
    // ERRORES — MOVIMIENTOS DE STOCK
    // ═══════════════════════════════════════════════════

    /// <summary>Tipo de movimiento no reconocido.</summary>
    public static string Error_InvalidMovementType =>
        _resourceManager.GetString(nameof(Error_InvalidMovementType), _culture)!;

    /// <summary>No existe estrategia para el tipo de movimiento.</summary>
    public static string Error_StrategyNotFound =>
        _resourceManager.GetString(nameof(Error_StrategyNotFound), _culture)!;

    // ═══════════════════════════════════════════════════
    // ERRORES — INFRAESTRUCTURA / RUNTIME
    // ═══════════════════════════════════════════════════

    /// <summary>JWT Secret no está configurado.</summary>
    public static string Error_JwtSecretNotConfigured =>
        _resourceManager.GetString(nameof(Error_JwtSecretNotConfigured), _culture)!;

    /// <summary>No se puede acceder al valor de un resultado fallido.</summary>
    public static string Error_FailedResultAccess =>
        _resourceManager.GetString(nameof(Error_FailedResultAccess), _culture)!;

    /// <summary>Error de prueba generado desde /api/diagnostics/error.</summary>
    public static string Diag_DefaultTestError =>
        _resourceManager.GetString(nameof(Diag_DefaultTestError), _culture)!;

    // ═══════════════════════════════════════════════════
    // VALIDACIONES — MOVIMIENTOS DE STOCK
    // ═══════════════════════════════════════════════════

    /// <summary>El ID del producto es obligatorio.</summary>
    public static string Val_Movement_ProductIdRequired =>
        _resourceManager.GetString(nameof(Val_Movement_ProductIdRequired), _culture)!;

    /// <summary>El tipo de movimiento es obligatorio.</summary>
    public static string Val_Movement_TypeRequired =>
        _resourceManager.GetString(nameof(Val_Movement_TypeRequired), _culture)!;

    /// <summary>El tipo de movimiento debe ser 'Inbound' o 'Outbound'.</summary>
    public static string Val_Movement_TypeInvalid =>
        _resourceManager.GetString(nameof(Val_Movement_TypeInvalid), _culture)!;

    /// <summary>La cantidad debe ser mayor a cero.</summary>
    public static string Val_Movement_QuantityGreaterThanZero =>
        _resourceManager.GetString(nameof(Val_Movement_QuantityGreaterThanZero), _culture)!;
}
