// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetInventory.Infrastructure.Persistence;

#nullable disable

namespace NetInventory.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260407172217_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.25");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("tbRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<string>("RoleId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("tbRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        ;

                    b.Property<int>("AccessFailedCount")
                        ;

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        ;

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        ;

                    b.Property<bool>("EmailConfirmed")
                        ;

                    b.Property<bool>("LockoutEnabled")
                        ;

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        ;

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("PasswordHash")
                        ;

                    b.Property<string>("PhoneNumber")
                        ;

                    b.Property<bool>("PhoneNumberConfirmed")
                        ;

                    b.Property<string>("SecurityStamp")
                        ;

                    b.Property<bool>("TwoFactorEnabled")
                        ;

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("tbUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("ClaimType")
                        ;

                    b.Property<string>("ClaimValue")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("tbUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("ProviderKey")
                        ;

                    b.Property<string>("ProviderDisplayName")
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("tbUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        ;

                    b.Property<string>("RoleId")
                        ;

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("tbUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        ;

                    b.Property<string>("LoginProvider")
                        ;

                    b.Property<string>("Name")
                        ;

                    b.Property<string>("Value")
                        ;

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("tbUserTokens", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.AuditConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<bool>("IsEnabled")
                        ;

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        ;

                    b.Property<string>("UrlPattern")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.HasKey("Id");

                    b.ToTable("tbAuditConfigs", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<long>("DurationMs")
                        ;

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        ;

                    b.Property<DateTime>("OccurredAt")
                        ;

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("QueryString")
                        .HasMaxLength(1000)
                        ;

                    b.Property<string>("RequestBody")
                        .HasMaxLength(8000)
                        ;

                    b.Property<string>("ResponseBody")
                        .HasMaxLength(8000)
                        ;

                    b.Property<int>("StatusCode")
                        ;

                    b.Property<string>("UserEmail")
                        .HasMaxLength(256)
                        ;

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAt");

                    b.ToTable("tbAuditLogs", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.ErrorLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(100)
                        ;

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(2000)
                        ;

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        ;

                    b.Property<DateTime>("OccurredAt")
                        ;

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        ;

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<string>("StackTrace")
                        .HasMaxLength(8000)
                        ;

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.ToTable("tbErrorLogs", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.GeneralTable", b =>
                {
                    b.Property<int>("Id")
                        ;

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.HasKey("Id");

                    b.ToTable("tbGeneralTable", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.GeneralValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        ;

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<bool>("IsActive")
                        ;

                    b.Property<int?>("ParentId")
                        ;

                    b.Property<int>("SortOrder")
                        ;

                    b.Property<int>("TableId")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("TableId", "Code")
                        .IsUnique();

                    b.ToTable("tbGeneralValues", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        ;

                    b.Property<int>("CategoryTableId")
                        ;

                    b.Property<DateTime>("CreatedAt")
                        ;

                    b.Property<string>("CreatedBy")
                        ;

                    b.Property<int>("MaxStock")
                        
                        .HasDefaultValue(0);

                    b.Property<int>("MinStock")
                        
                        .HasDefaultValue(0);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        ;

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        ;

                    b.Property<int>("QuantityInStock")
                        ;

                    b.Property<string>("UpdatedBy")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("tbProducts", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<DateTime>("ExpiresAt")
                        ;

                    b.Property<bool>("IsRevoked")
                        ;

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(128)
                        ;

                    b.Property<string>("UserId")
                        .IsRequired()
                        ;

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.ToTable("tbRefreshTokens", (string)null);
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        ;

                    b.Property<string>("CreatedBy")
                        ;

                    b.Property<Guid>("ProductId")
                        ;

                    b.Property<int>("Quantity")
                        ;

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        ;

                    b.Property<DateTime>("Timestamp")
                        ;

                    b.Property<int>("Type")
                        ;

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("tbStockMovements", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.GeneralValue", b =>
                {
                    b.HasOne("NetInventory.Domain.Entities.GeneralValue", null)
                        .WithMany()
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NetInventory.Domain.Entities.GeneralTable", null)
                        .WithMany()
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.Product", b =>
                {
                    b.OwnsOne("NetInventory.Domain.ValueObjects.Money", "UnitPrice", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                ;

                            b1.Property<decimal>("Amount")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("UnitPrice");

                            b1.HasKey("ProductId");

                            b1.ToTable("tbProducts");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.OwnsOne("NetInventory.Domain.ValueObjects.Sku", "SKU", b1 =>
                        {
                            b1.Property<Guid>("ProductId")
                                ;

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                
                                .HasColumnName("SKU");

                            b1.HasKey("ProductId");

                            b1.ToTable("tbProducts");

                            b1.WithOwner()
                                .HasForeignKey("ProductId");
                        });

                    b.Navigation("SKU")
                        .IsRequired();

                    b.Navigation("UnitPrice")
                        .IsRequired();
                });

            modelBuilder.Entity("NetInventory.Domain.Entities.StockMovement", b =>
                {
                    b.HasOne("NetInventory.Domain.Entities.Product", null)
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
